### ISSUE TITLE
Refresh when selecting different category.

### ISSUE THREAD

**Issue by DeeBeeDouble** [Davidoc26/wallpaper-selector#1]
As the title says, it would be great if the app could automatically refresh itself once a new category is selected. Currently, you have to re-open the app to apply the change, which is rather inconvenient.

**Comment by Davidoc26** [comment]
Currently the changes are being applied, but you have to scroll down to load the wallpapers of the new category.

Generally yes, we are losing some pages this way, I will fix it very soon.

**Comment by DeeBeeDouble** [comment]
Good job, works well now
