### ISSUE TITLE
Cannot find the  location of previous wallpaper

### ISSUE THREAD

**Issue by pakosaan** [Davidoc26/wallpaper-selector#12]
Is the wallpaper even downloaded or not?

**Comment by pakosaan** [comment]
/home/user/.var/app/io.github.davidoc26.wallpaper_selector/data is the location but is there any way to changer the default address ??

**Comment by Davidoc26** [comment]
Since this is a flatpak application, it uses the XDG_DATA_HOME environment variable and stores the downloaded wallpaper there. You can try reassigning this variable via flatseal, but I don't guarantee that it will work.
