### ISSUE TITLE
Add option for Nsfw

### ISSUE THREAD

**Issue by DeeBeeDouble** [Davidoc26/wallpaper-selector#6]
Currently, when selecting categories such as anime or people, the results contain NSFW content. There should probably be an option to disable NSFW and only display SFW images, like it's the case on wallhavens website.

**Comment by Davidoc26** [comment]
Unfortunately, nothing can be done about it.

Currently, this is up to wallhaven itself as it cannot show NSFW content unless you are registered. By default (as it is now) only sfw content is displayed. If suddenly you see nsfw content, this means that you can see it on the site itself with the selected sfw.
